### ISSUE TITLE
Frameless to NDI and higher performance

### ISSUE THREAD

**Issue by fgolman** [rse/vingester#6] opened 2021-04-09 04:27 UTC
Would love to see the higher performance, GPU based Frameless mode combined with the NDI output of the Headless mode.

**Comment by rse** [comment] 2021-04-09 07:26
This would be also my wish ;-) The problem is that Electron uses Chromium and the Vingester "Headless" mode can only use Electron/Chromium's "offscreen rendering" functionality and this in turn actually uses the GPU, BUT only partially and especially cannot use it for the frame capturing part. As a result, this offscreen rendering with enabled GPU hardware acceleration is SLOWER than with a disabled GPU hardware acceleration.

But I'm already working on this. We have a few other options to speed things up: one is to get the "dirty" area feature working which Electron at least theoretically provides to speed up capturing (unfortunately for me it still never worked as expected), the other is to reduce the framerate of browsers which are currently no in preview or in program (according to the NDI tally reporting). The tally support is already in Vingester 1.3.1, the adaptive framerate support I'm currently already working on. These things can help to increase the overall performance. How much, we will have to see. Expect those features in Vingester 1.4...

**Comment by rse** [comment] 2021-04-11 12:42
Vingester 1.5.0 now has an "Adaptive" option for NDI which reduces the FPS in capturing when the NDI receiver Tally information shows that it is not important to send full FPS (because the stream is still not in preview or even program). This somewhat should help to improve the overall performance in case of multiple(!) streams. For a single stream this still cannot help, of course. Next step for me is to determine how to use the dirty feature of Electron's capturing mechanism to speed up the FPS for a single browser capturing process.

**Comment by rse** [comment] 2021-04-18 22:25
I've tested Vingester's performance now on different PCs and the outcome is now shown in the README file:

- In **"Frameless"** mode, with **enabled** GPU Hardware Acceleration   and **disabled** previews, a PC based on a 6-core i5-10600K CPU and   running under Windows 10 can ingest **9** OBS.Ninja sessions with 720p30   at about 80% average system load and without performance penalties.

- In **"Frameless"** mode, with **enabled** GPU Hardware Acceleration and **disabled** previews, a PC based on a 8-core i7-11700KF CPU and running under Windows 10 can ingest **18** OBS.Ninja sessions with 720p30 at about 40% average system load and without performance penalties.

- In **"Headless"** mode, with **disabled** GPU Hardware Acceleration and **disabled** previews, a PC based on a 6-core i5-10600K CPU and running under Windows 10 can ingest **4** OBS.Ninja sessions with 720p30 at about 80% average system load and without performance penalties.

- In **"Headless"** mode, with **disabled** GPU Hardware Acceleration and **disabled** previews, a PC based on a 8-core i7-11700KF CPU and running under Windows 10 can ingest **8** OBS.Ninja sessions with 720p30 at about 60% average system load and without performance penalties.

This means that the NDI performance now is already at least a decent one. Yes, it still requires lots of CPU power and as a consequence a high-performance computer, but 4-8 OBS.Ninja sessions is now an acceptable performance. I'll certainly try to further improve on this, but the main bottleneck is the Inter-Process Communication (IPC) mechanism of the underlying Electron technology which currently does not allow to squeeze out a lot more. So, allow me to close this issue for now.

**Closed by rse** 2021-04-18 22:25 UTC
Labels: enhancement
