### ISSUE TITLE
Singular graphics outputs behaving strangely.

### ISSUE THREAD

**Issue by TenisanIsWorking** [rse/vingester#20] opened 2021-04-30 00:48 UTC
Not sure if you're familiar with Singular.live, but we're using multiple channels of Singular graphics in vMix for some live productions. Hoping to move the browser source load to a different machine on the same network.

It seems that the NDI sources generated by Vingester when loading a Singular output URL do not have a transparent background for some reason, and also load at 1848x1040 even when set to 1920x1080 in the interface.

Let me know what other information I can provide, thank you!!

**Comment by rse** [comment] 2021-04-30 10:58
Well, the background color can be controlled by you in Vingester. Set it to "transparent". If the content then is still not transparent, this is because the Singular.live uses a stylesheet with a non-transparent background, I guess. The sizing issue might be also related to the stylesheets of Singular.live. Can you share an example URL of Singular.live, so I can reproduce the issues you have more easily?

**Comment by rse** [comment] 2021-04-30 17:37
Ah, ok, the transparency issue I see myself now, too. But it happens only for the frameless (window) mode. For the headless (NDI) mode is looks just fine. I'll check what I can do to fix the frameless mode. The sizing issue I cannot see. I've used 1280x720 and the NDI output is exactly of this size and the Singular.live example content displays just fine for me.

**Comment by rse** [comment] 2021-04-30 17:39
Well, the question for me is: in frameless mode a transparent window would not help very much as in screen capturing one cannot use a transparent background. One would just capture the desktop background instead. And this is as bad as capturing a background of the Vingester window itself. So, for the frameless (window) mode of operation I would recommend to use "#00ff##" for the "Color" field in Vingester and then apply a chroma key filter in your mixing software.

**Comment by rse** [comment] 2021-04-30 17:51
A transparent "Color" field in Vingester 1.7.2 will not also lead to a really transparent window. Whether this helps someone is another reasons (depends on your desktop background), but this is at least consistent. The sizing issue I cannot repeat myself, I'll close this PR now.

**Closed by rse** 2021-04-30 17:51 UTC

**Comment by TenisanIsWorking** [comment] 2021-04-30 18:05
Oh interesting, I specifically have this issues in Headless mode.
I'm curious, if you pick specifically 1920x1080, is the NDI output exactly that size? Because I also see that when I pick 1280x720, I get exactly 720p, but when I pick 1920x1080, I get 1848x1040.

I just tested with some of the test content on https://www.singular.live/try
Still not getting transparency, even in headless mode, and trying to select 1920x1080 still leads to 1848x1040. Not sure if it will work for you, but this is the ouptut URL I have loaded up:
https://app.singular.live/output/09huNj2k3Th7GcTpaK6xQg/Default?aspect=16:9

Here's a couple screenshots of how I have things configured, and what the ouput looks like in NDI Studio Monitor:
![image](https://user-images.githubusercontent.com/83435845/116735790-db5cfd80-a9a3-11eb-8d34-a16b3e8a9506.png)
![image](https://user-images.githubusercontent.com/83435845/116735908-06475180-a9a4-11eb-811d-f406dbaa1d2d.png)

**Comment by JBraddockm** [comment] 2021-05-12 17:53
As an organisation for which I do some works is also planning to use Singular Live, I've tested it on OBS and both the transparency and resolution seems to work.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/16445610/118021002-add46480-b352-11eb-9edd-81aff30bc64d.png">
