### ISSUE TITLE
NDI transparency issue

### ISSUE THREAD

**Issue by GoranKovac** [rse/vingester#52] opened 2021-08-27 08:36 UTC
I cannot make transparency work with NDI (headless mode only). Page shows normal in Vmix as browser source:
![image](https://user-images.githubusercontent.com/19614757/131098924-e1374d68-262a-446a-a224-6ea1ad348d0b.png)
![image](https://user-images.githubusercontent.com/19614757/131097442-25a81fe9-8877-4926-962b-f55abba5ecd9.png)

But if I enable BOTH Frameless and Headless then NDI output has alpha (but its not the same, less color on the NDI):
![image](https://user-images.githubusercontent.com/19614757/131098855-b50b2710-c491-4c4c-bca4-cdebf20ccfcd.png)
![image](https://user-images.githubusercontent.com/19614757/131097639-e1e1a297-c321-4b89-b3e4-b6009a75b967.png)

Tried it on 3 latest versions, not sure if I'm doing something wrong or this is expected configuration for alpha to work on NDI?

Anyway this web page is very simplistic nothing special, background is set to rgba(0,0,0,0)

EDIT: Enabling GPU gets alpha to work on HEADLESS mode only, but still results are not the same
![image](https://user-images.githubusercontent.com/19614757/131103106-b33cfc8b-1d16-405f-8886-b128d1336230.png)
![image](https://user-images.githubusercontent.com/19614757/131103067-7bad8b74-0f38-4d07-a927-8b32f3154f9b.png)

**Comment by rse** [comment] 2021-09-03 23:24
I've currently no VMix at hand (would have to install a trail version first), so I cannot quickly test this. But Vingester internally does not really fiddle with the transparency such much that it is even related to the GPU support of Electron/Chromium. Hence, I suggest that you at least retry with the new Vingester 2.6.0 which has a more recent Electron/Chromium version now. Perhaps it was really a bug in Electron/Chromium...

**Comment by GoranKovac** [comment] 2021-09-04 07:14
Headless mode in Latest version (2.6.0) does not work. Not getting anything and there is nothing in the preview (even the example configurations do not work) and also nothing on NDI network is found
![image](https://user-images.githubusercontent.com/19614757/132086176-6cb62c80-ab69-4e42-aff3-2a34c85e69e7.png)

**Comment by rse** [comment] 2021-09-04 08:16
Ok, then we now have two bugs: with the newer Electron the preview is broken and the transparency issue still exists. Good to know that it is also repeatable in OBS Studio. Then I'll check with OBS Studio. Can you attach me your particular sample Web page from your original test, just to ensure I can easily repeat exactly your situation?

**Comment by GoranKovac** [comment] 2021-09-04 08:45
[vingester_test.zip](https://github.com/rse/vingester/files/7109463/vingester_test.zip)
Tested with:
VMix browser source - transparency works as expected
Obs browser source - transparency works as expected
Vingester headless mode, no transparency (you can immediately see it in preview there is a white background and that bg is present in NDI)
![image](https://user-images.githubusercontent.com/19614757/132088673-1575c20c-4c9d-46bf-b6d7-b88b81e03ed8.png)

**Comment by rse** [comment] 2021-10-02 09:33
The issue is unrelated to VMix. I'm now able to repeat it also in a different context. I'll investigate to find out why the transparency is broken for the NDI-only case.

**Comment by rse** [comment] 2021-10-02 22:18
This will be now fixed with Vingester 2.6.5.

**Closed by rse** 2021-10-02 22:18 UTC
Labels: bug
