### ISSUE TITLE
Transparency issue with NDI-only

### ISSUE THREAD

**Issue by FlowingSPDG** [rse/vingester#62] opened 2021-12-23 11:24 UTC
Hello, thank you again for awesome project.

I think #52 is still not fixed in 2.7.0. Tested with Windows10 NDI, received by both of OBS Studio NDI and vMix.
When I enable Headless, transparency is available for NDI.

**Comment by rse** [comment] 2022-04-04 19:28
I've tried it out with Vingester 2.8.0 and NDI-only outputs and a Webpage with a transparent background (and a few lower-thirds on it) displayed just fine in a video mixer like vMix.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/221273/161617615-eb44272c-eb75-4717-9000-11394aaeb426.png">

I allow me to close this issue for now. If you still have trouble with transparency, please re-open this issue and give me a few more hints what particular Web content you are trying to display. Perhaps the problem is with the Web content itself?

**Closed by rse** 2022-04-04 19:28 UTC
Labels: bug

**Comment by FlowingSPDG** [comment] 2022-04-05 06:11
Possibly yeah, I did not have much time to check that web content has transparency background, silly me!
Thank you for checking issue.
