### ISSUE TITLE
Low framerate and cracking audio with 1080p NDI Output (headless mode)

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#3] opened 2021-04-06 06:32 UTC
Hello, I'm testing Vingester because I intensively use obs.ninja in my workflow. Until today, to achieve the same result, I've been using various Google Chrome instances, open in fullscreen on various external displays connected to my Macs.

Regarding the NDI Output (headless mode) of Vingester, I found out that I cannot achieve more da 18 fps. I have a MacBook Pro (16-inch, 2019) 2,4 GHz 8-Core Intel Core i9. Is that normal?

Other than that, the audio is cracking and, only in headless mode, the preview window is not working.

<img width="896" alt="Screenshot 2021-04-06 at 08 29 07" src="https://user-images.githubusercontent.com/67373152/113668427-7ec33700-96b2-11eb-9834-9fb9242432fe.png">

**Comment by rse** [comment] 2021-04-06 06:49
In Vingester >= 1.2.0 I've fixed the audio crackling issue by switching from PCM to OPUS internal audio processing. So, if you use 1.2.0 or 1.3.0 this should be gone. According to the reduced FPS rate: yes, the headless mode cannot use GPU hardware acceleration and as a result depends on your CPU performance and on a 2.4 GHz machine this can be. On my 6 core 4 GHz machine I at least can run 4 NDI sessions with 30 fps, at least if GPU acceleration is DISABLED (you have it still enabled in your screenshot). The preview issue I've to check: what particular version have you used?

**Comment by rse** [comment] 2021-04-06 06:51
Oh, BTW, the interesting point in your screenshot is that the NDI monitor says it receives the video at 16 fps while Vingester has calculated that it runs at 30 fps. This is strange. Especially that your "CPU: 5+1=6 / 33" means that Vingester needs 5 ms for video encoding (and 1 ms for audio) and still would have enough room (as 30 fps means 33 ms for encoding maximum time). Strange. I've no clue why less fps are seen by Sienna NDI Monitor....

**Comment by Gabriele-LS** [comment] 2021-04-06 07:01
Hello Ralf, the audio cracking is there only if GPU hardware acceleration is enabled. Regarding the framerate, the mimoLive source monitor is showing the same fps as the Sienna NDI Monitor.

**Comment by Gabriele-LS** [comment] 2021-04-06 07:11
P.S. Apparently, the audio crackling is there only with the Sienna NDI Monitor. mimoLive audio is correct, no matter if GPU hardware acceleration is on or off.

Anyway, I attach screenshot of mimoLive, showing the fps.

<img width="1454" alt="Screenshot 2021-04-06 at 09 10 58" src="https://user-images.githubusercontent.com/67373152/113672425-0e1f1900-96b8-11eb-98e4-438e9447f3b8.png">

**Comment by rse** [comment] 2021-04-06 21:40
Ok, so the audio crackling seems to be not related to Vingester, but the lower FPS seems to be. I'll check this...

**Comment by Gabriele-LS** [comment] 2021-04-07 05:59
Capturing the Vingester window with Newtek NDI Scan Converter gives me 30 fps (this seems to be intentionally limited).

Other issues I found capturing the Vingester window are:

- the rounded corners of the window
- the three (close, minimize and maximize) buttons in the upper left corner

<img width="983" alt="Screenshot 2021-04-07 at 07 55 23" src="https://user-images.githubusercontent.com/67373152/113817583-dd51e900-9776-11eb-94c8-9cb8cc7f8e83.png">

**Comment by rse** [comment] 2021-04-07 06:25
Yes, the rounded corners are macOS-specific and cannot be changed by an application as far as I know. I'm primarily using Vingester under Windows where no such corners exists. But the buttons I think I can force to be not visible. I'll try to get rid of them under macOS.

**Comment by rse** [comment] 2021-04-07 06:32
OK, I've checked: the forthcoming Electron versions will have an API ([roundedCorners](https://github.com/electron/electron/commit/af4a050a1bc386194e4a5a8d53b982e4c71b0bff)) to remove the rounded corners under macOS. Unfortunately this is still not available in the release versions. So I can change this the first time in a few months, I think. Let's await this new feature...

**Comment by Gabriele-LS** [comment] 2021-04-07 06:36
Great! I hope you will also be able to find out why NDI is not performing as expected.

**Comment by rse** [comment] 2021-04-07 06:37
The three window buttons now will be gone in the next version of Vingester. I've added a fix for this now.

**Comment by rse** [comment] 2021-04-07 06:59
The roundedCorners settings I've now already commited ahead of time. It now allows browser windows without corners (see screenshot). Unfortunately, this will need Electron 13 which currently is still in beta and expected to be released end of May according to the Electron [timeline](https://www.electronjs.org/docs/tutorial/electron-timelines)

<img width="738" alt="Screenshot 2021-04-07 at 08 56 09" src="https://user-images.githubusercontent.com/221273/113823648-2efe7180-977f-11eb-8a88-522112519485.png">

**Comment by Gabriele-LS** [comment] 2021-04-07 07:25
Excellent! Are these new improvements going to be part of a new Vingester beta version?

**Comment by rse** [comment] 2021-04-07 10:59
The problem is that Vingester is based on the underlying Electron technology and the non-rounded corners feature is not available in a stable release version of Electron. So Vingester cannot use the non-rounded-corners until Electron 13 will be released end of May. If you really need it beforehand, the only possibility is to build Vingester yourself from the sources and switch the Electron dependency in the file `package.json` from the release version 12.0.2 to 13.0.0-beta.11

**Comment by rse** [comment] 2021-04-11 14:27
I'm now closing this issue because the button issue has been addressed and the low framerate will be still addressed in issue #6.

**Closed by rse** 2021-04-11 14:27 UTC
Labels: bug, enhancement

**Comment by rse** [comment] 2021-04-16 22:40
Just a heads-up: I found out why Sierra NDI Monitor showed just 25 fps for some content! It's very simple: Sierra NDI Monitor is RIGHT, it really receives just 25 fps for some content, BUT it is not Vingester's fault! Vingester tells the underlying Chromium engine that a framerate of e.g. 30 is wished. And it really starts with this framerate. But if the content just updates with 25 fps, Vingester will receive just 25 fps. And the reason for all my tests was simple that the Web Contents I checked were YouTube videos and those videos were 1080p25 videos!

Check it out yourself: The Web Contents https://www.youtube.com/embed/BKorP55Aqvg?autoplay=1 has 25 FPS in the source while the https://www.youtube.com/embed/79ImZE0K7xc?autoplay=1 actually is a 60 FPS video. When you tell Vingester you want 30 FPS with the first, you at the end can still receive 25 FPS because the source is just 25 FPS. When you tell Vingester you want 30 FPS with the second one, you get 30 FPS. If you tell Vingester you want 60 FPS with the second one, you even will get 60 FPS in Sierra NDI Monitor. So, this is not a performance issue inside Vingester. It really is just a matter of the frame rate of the source!

**Comment by Gabriele-LS** [comment] 2021-04-17 05:12
Hello @rse, I wanted to make a test with the videos you recommended but Vingester became unresponsive multiple times. I had to force quit it. This is how it is set up. After 10-15 seconds of playing, Vingester buttons start not responding anymore and, just after, the video stops playing in the NDI Monitor.

<img width="1540" alt="Screenshot 2021-04-17 at 07 09 56" src="https://user-images.githubusercontent.com/67373152/115102569-f95e4300-9f4b-11eb-9c92-13d31e4a7eb1.png">

**Comment by rse** [comment] 2021-04-17 08:20
I guess this is a local performance issue. Perhaps Vingester's off-screen rendering cannot cope with the 60fps of the video. On my system (Windows 10, 6-core i5) it worked just fine the entire video. Hmm... I've no clue what we could do here.

**Comment by Gabriele-LS** [comment] 2021-04-17 08:31
I see. The max fps I can get without issues – both with NDI Scan Converter and Vingester – is 30 fps.
