### ISSUE TITLE
RTMP & UDP mode see to have 1 sec AV-Sync issue with Audio ahead

### ISSUE THREAD

**Issue by regstuff** [rse/vingester#30] opened 2021-05-17 08:44 UTC
Hi,
Thanks for the great app. Super useful!
I'm using FFMPEG sink to output to MPEG-TS. Arguments given are udp://127.0.0.1:5001
Then as a test, I'm pulling it into ffmpeg in a terminal with: ffmpeg -i udp://127.0.0.1:5001 -vcodec copy -f flv "C:\Users\Streaming\Desktop\aplay.flv"
I see that the audio is ahead by about a second in the resulting flv. Similar issues persists even when output is mp4 or if sink is set to rtmp.
CPU usage is 50-60%. Frameless mode does not show this av sync issue.
Any clue what I'm doing wrong.

As an aside, many times I'm only interested in pulling the audio from a url, and I plan to run Vingester in a headless server in the cloud. Is there any way to not render the video in Vingester & therefore save on CPU usage?

**Comment by rse** [comment] 2021-05-31 21:45
That video and audio go out of sync is a usual problem I've facing in many processing pipelines, not just in Vingester. The reason always is that the video and audio processing requires different amount of CPU power (usually, audio is faster than video unless you are using a comprehensive VST plugin chain in your pipeline where in one of my OBS Studio setups then have audio to be 100ms behind video). In those cases the usual fix is to add delay to audio or video. In your situation you have to add a delay on the audio. See the "Delay" fields in the configuration dialogs.

If you are running a webpage where only audio plays, Vingester should be able to process just this audio and the video processing should be very harmless if you at least use the NDI sink and configure a "VIDEO: Frame Rate" of just 1.

**Comment by rse** [comment] 2021-05-31 21:51
I've checked the code of Vingester. Actually, you are allowed to even enter "0" for the "OUTPUT2 > VIDEO > Frame Rate" field and this internally really means that an audio-only NDI stream is sent. I've checked it and received the audio stream just fine.

**Comment by regstuff** [comment] 2021-06-03 08:31
Hi
Tried setting Frame Rate to 0. NDI works but the CPU usage is still quite high - as high as setting framerate to 25.
I tried with a YouTube video link. Is the CPU usage expected to be this high when framerate is 0?

**Comment by rse** [comment] 2021-06-03 08:37
No, I would expect a noticable lower CPU utilization. I'll check the code once again. Perhaps not "enough" of the video capturing code is skipped...

**Comment by rse** [comment] 2021-06-03 08:40
One possibility can be that you have the preview (at the right top corner of each browser instance in the control UI) activated. Then the video has to be still captured. Can this be the case for you?

**Comment by rse** [comment] 2021-06-03 08:42
The other possibility is that instead of the preview you have the "Adaptive" mode enabled (check the corresponding field). If either preview or adaptive mode is enabled, the current code still performs capturing. For preview I cannot change it, for adaptive enabled plus frame rate set to "0" I can adjust the code and no longer capture in the future. But can one of those configuration toggles your problem?

**Comment by regstuff** [comment] 2021-06-03 12:12
HI. Thanks for the reply. Have attached a screenshot of the running browser instance.
CPU is quite high as you can see. Preview (in the bottom right for me, not top right) is off. Frameless mode is off. NDI is on. Framerate set to 0. Resolution is set to 640x360. Anything else that I need to change?
![snapshot](https://user-images.githubusercontent.com/6016831/120642780-f1724800-c492-11eb-8ede-3716d6977e71.JPG)

**Comment by regstuff** [comment] 2021-06-03 12:43
UPDATE: Have updated to your latest 2.2.2.0 version. Now I am not getting any output on Headless mode at all. No NDI or FFmpeg output! This is the case irrespective of FrameRate setting - whether 0 or otherwise.
CPU usage seems to have come down drastically though.
Frameless still works as intended.

**Comment by rse** [comment] 2021-06-03 13:20
That's strange. First, with 2.2.2 my CPU utilization with exactly your config is rather low:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/221273/120651210-d0076100-c47e-11eb-913b-6a754ff9ee30.png">

And I still get the audio-only streem via NDI. So, it seems just fine. Well, at least under macOS where I'm currently working. Hmmmm.... I've currently no clue where the difference between you and me is.

PS: But I see a new bug I've introduced by support Frame Rate 0: the information "CPU: 0+NaN=NaN / 17 ms/f" display on the right hand side is at least broken (will be fixed soon).

**Comment by regstuff** [comment] 2021-06-03 14:50
Using the older version - 2.0.1 I think works. Can see NDI output etc. Though the CPU issue is there.
In the latest version, CPU usage is low, but no output.
The settings are the same in both versions.

**Comment by rse** [comment] 2021-06-03 23:23
The FFmpeg trouble you had seems to be related to #34 and this should be now fixed in Vingester 2.2.3

**Comment by regstuff** [comment] 2021-06-04 08:53
Tested NDI output in Headless mode in two different PCs with Win 10.
NDI output is not detected by OBS on NDI Studio Monitor in 2.2.2 - CPU usage is lower.
NDI output is detected in the latest 2.2.3 version - CPU usage is higher though. 
However, I find that changing the resolution reduces CPU usage in 2.2.3. For now I am keeping the resolution at 192x108 and seeing a 5fivefold drop in CPU usage as compared to keeping it as 1920x1080.

**Comment by rse** [comment] 2021-06-04 10:58
Ok, so NDI works again in 2.2.3. Fine. That the CPU usage was low in 2.2.2 was a side-effects of a not working headless mode at all. So, this cannot be compared. That the CPU usage drops in 2.2.3 with the reduced resolution is expected. That it does not drop by the same factor is because there is a "base" CPU usage caused by the capturing process at all. Check out the hints under https://vingester.app/guide/#/performance in the Vingester Guide, too.

**Closed by rse** 2021-06-04 10:58 UTC
